---
- name: Install required dependencies on Ubuntu >= 20.04
  apt:
    name: gnupg
    state: present
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version is version('20.04', '>=')

- name: Remove revoked Telegraf repository key
  file:
    path: "/etc/apt/trusted.gpg.d/telegraf.gpg"
    state: absent

- name: Install Telegraf repository key
  get_url:
    url: "{{ telegraf_signing_key_url }}"
    checksum: "{{ telegraf_signing_key_checksum | d(omit) }}"
    dest: "/etc/apt/trusted.gpg.d/telegraf.asc"
    mode: "0644"

- name: Install Telegraf repository
  apt_repository:
    repo: "deb https://repos.influxdata.com/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes

- name: Install Telegraf
  apt:
    name: telegraf
    state: present
  ignore_errors: "{{ ansible_check_mode }}"

- name: Install Telegraf configuration
  template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
    mode: 0644
  with_items:
    - etc/telegraf/telegraf.conf
    - etc/telegraf/telegraf.d/ansible-inputs.conf
    - etc/telegraf/telegraf.d/ansible-processors.conf
  notify: restart telegraf
  vars:
    _telegraf_outputs: "{{ telegraf_outputs | combine(telegraf_group_outputs, recursive=True) | combine(telegraf_host_outputs, recursive=True) }}"
    _telegraf_inputs: "{{ telegraf_inputs | combine(telegraf_group_inputs, recursive=True) | combine(telegraf_host_inputs, recursive=True) }}"
    _telegraf_processors: "{{ telegraf_processors | combine(telegraf_group_processors, recursive=True) | combine(telegraf_host_processors, recursive=True) }}"
    _telegraf_tags: "{{ telegraf_tags | combine(telegraf_group_tags) | combine(telegraf_host_tags) }}"

- name: Add telegraf user to required groups
  user:
    name: telegraf
    groups: "{{ item }}"
    append: true
  # groups may not exist yet ¯\_(ツ)_/¯
  ignore_errors: true # noqa ignore-errors
  when: item in _telegraf_inputs
  loop:
    - docker
  notify: restart telegraf
  vars:
    _telegraf_inputs: "{{ telegraf_inputs | combine(telegraf_group_inputs) | combine(telegraf_host_inputs) }}"

- name: Enable and start Telegraf
  service:
    name: telegraf
    enabled: "{{ telegraf_service_enabled }}"
    state: "{{ telegraf_service_state }}"
  ignore_errors: "{{ ansible_check_mode }}"
