---
- name: Restart telegraf
  listen: restart telegraf
  ansible.builtin.service:
    name: telegraf
    state: "{{ telegraf_restart_handler_state }}" # noqa args[module]
  ignore_errors: "{{ ansible_check_mode }}"
