---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Ensure Telegraf is installed
      stat:
        path: "/usr/bin/telegraf"
      register: result
      changed_when: false
      failed_when: result.stat.isreg is not defined or not result.stat.isreg

    - name: Ensure Telegraf is running
      service:
        name: telegraf
        state: started
      check_mode: true
      register: result
      failed_when: result is changed

    - name: Ensure Telegraf configuration files are correct
      copy:
        src: "{{ item | basename }}"
        dest: "/etc/telegraf/{{ item }}"
        mode: "0644"
      check_mode: true
      diff: true
      register: result
      failed_when: result is changed
      loop:
        - telegraf.conf
        - telegraf.d/ansible-inputs.conf
        - telegraf.d/ansible-processors.conf
