---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Ensure Telegraf is installed
      stat:
        path: "/usr/bin/telegraf"
      register: result
      changed_when: false
      failed_when: result.stat.isreg is not defined or not result.stat.isreg

    - name: Ensure Telegraf is running
      service:
        name: telegraf
        state: started
      check_mode: true
      register: _telegraf_service
      failed_when: _telegraf_service.changed

    - name: Ensure configuration options are set correctly
      community.general.ini_file: # noqa risky-file-permissions
        no_extra_spaces: false
        path: "/etc/telegraf/telegraf.conf"
        section: "{{ item.section }}"
        option: "{{ item.option }}"
        value: "{{ item.value }}"
        state: present
      loop:
        # the indented options and quoted values are required so that the formatting
        # matches that used in the telegraf configuration files
        - section: global_tags
          option: "  datacentre"
          value: '"example"'
        - section: agent
          option: "  interval"
          value: '"30s"'
        - section: agent
          option: "  hostname"
          value: '"ansible_telegraf"'
        - section: "[outputs.influxdb]"
          option: "  retention_policy"
          value: '""'
        - section: "[outputs.influxdb]"
          option: "  database"
          value: '"telegraf"'
        - section: "[outputs.influxdb]"
          option: "  urls"
          value: "['http://stats.example.local:8086']"
      check_mode: true
      register: _telegraf_config
      failed_when: _telegraf_config.changed

    - name: Ensure input options are set correctly
      copy: # noqa risky-file-permissions
        dest: "/etc/telegraf/telegraf.d/ansible-inputs.conf"
        content: |+
          # Ansible managed: Do NOT edit this file manually!

          [[inputs.cpu]]
            collect_cpu_time = true
            percpu = true
            report_active = false
            totalcpu = true

          [[inputs.disk]]
            ignore_fs = ['tmpfs', 'devtmpfs', 'devfs', 'iso9660', 'overlay', 'aufs', 'squashfs']

          [[inputs.diskio]]

          [[inputs.kernel]]

          [[inputs.mem]]

          [[inputs.swap]]

          [[inputs.system]]

      check_mode: true
      register: _telegraf_config
      failed_when: _telegraf_config.changed

    - name: Ensure processor configuration is correct
      copy: # noqa risky-file-permissions
        dest: "/etc/telegraf/telegraf.d/ansible-processors.conf"
        content: |+
          # Ansible managed: Do NOT edit this file manually!

          [[processors.regex]]
            namepass = ['net']
            [[processors.regex.tags]]
              key = "interface"
              pattern = "^eno1$"
              replacement = "eth0"

            [[processors.regex.tags]]
              key = "interface"
              pattern = "^ens1$"
              replacement = "eth1"

      check_mode: true
      register: _telegraf_config
      failed_when: _telegraf_config.changed
