# Ansible managed

[[processors.regex]]
  namepass = ["net"]
  [[processors.regex.tags]]
    key = "interface"
    pattern = "^eno1$"
    replacement = "eth0"

  [[processors.regex.tags]]
    key = "interface"
    pattern = "^ens1$"
    replacement = "eth1"

[[processors.test_processor]]
  [[processors.test_processor.nested1]]
    option1 = "value1"
    [[processors.test_processor.nested1.nested2]]
      option2 = "value2"
      [[processors.test_processor.nested1.nested2.nested3]]
        option3 = "value3"


