---
telegraf_agent_hostname: ansible_telegraf

telegraf_host_tags:
  datacentre: example

telegraf_outputs:
  influxdb:
    urls:
      - "http://stats.example.local:8086"
    database: "telegraf"
    retention_policy: ""
    write_consistency: "any"
    timeout: "5s"

telegraf_host_inputs:
  cpu:
    totalcpu: true
    percpu: true

telegraf_host_processors:
  regex:
    namepass:
      - "net"
    tag1:
      _name: tags
      key: "interface"
      pattern: "^eno1$"
      replacement: "eth0"

telegraf_sudo_defaults: "!logfile, !syslog, !pam_session"
telegraf_sudo_commands:
  - /usr/bin/ls /

telegraf_host_plugin_filters:
  input:
    diskio: "{{ inventory_hostname != 'instance' }}"
